// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXQKc3F91crq2g4tirk_hz9W80VOBmoI0',
    appId: '1:915621689789:web:3af8ba5b3840af8c79bad4',
    messagingSenderId: '915621689789',
    projectId: 'homify-5c8f1',
    authDomain: 'homify-5c8f1.firebaseapp.com',
    storageBucket: 'homify-5c8f1.firebasestorage.app',
    measurementId: 'G-YM97V87X09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYoYBf0QARYt_jY0UQ_-RXxKt3D3zIreQ',
    appId: '1:915621689789:android:093c8c46ccdfb3b679bad4',
    messagingSenderId: '915621689789',
    projectId: 'homify-5c8f1',
    storageBucket: 'homify-5c8f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUOUczvxF5JOTHy0F93elNMjFS9tSCpI',
    appId: '1:915621689789:ios:5a63205ad42a88b879bad4',
    messagingSenderId: '915621689789',
    projectId: 'homify-5c8f1',
    storageBucket: 'homify-5c8f1.firebasestorage.app',
    iosBundleId: 'com.example.homify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoUOUczvxF5JOTHy0F93elNMjFS9tSCpI',
    appId: '1:915621689789:ios:5a63205ad42a88b879bad4',
    messagingSenderId: '915621689789',
    projectId: 'homify-5c8f1',
    storageBucket: 'homify-5c8f1.firebasestorage.app',
    iosBundleId: 'com.example.homify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXQKc3F91crq2g4tirk_hz9W80VOBmoI0',
    appId: '1:915621689789:web:e7aeabd87b35816f79bad4',
    messagingSenderId: '915621689789',
    projectId: 'homify-5c8f1',
    authDomain: 'homify-5c8f1.firebaseapp.com',
    storageBucket: 'homify-5c8f1.firebasestorage.app',
    measurementId: 'G-RFX2HYM4QC',
  );
}
